before_script:
  - apt-get update -qq && apt-get install -y -qq pandoc pandoc-citeproc

pages:
  image: python:3.6-alpine
  script:
  - pip install -r requirements.txt
  - pelican -s publishconf.py -D
  - mkdir .public
  - cp -r output/* .public/
  - mv .public public
  - ls
  - ls public
  artifacts:
    paths:
    - public/
