image: python:3.6-alpine

pages:
  stage: test
  image: python:3.6-alpine
  script:
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - pelican -s publishconf.py -D
    - ls .
    - mkdir .public
    - cp -r output/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
